# Scanned bound route handlers for auth:
HANDLE_CONFIRMATION_RESENDING_GET = 'auth.handle_confirmation_resending_get'
HANDLE_CONFIRMATION_GET = 'auth.handle_confirmation_get'
HANDLE_PASSWORD_RESETTING_GET = 'auth.handle_password_resetting_get'
HANDLE_REGISTRATION_POST = 'auth.handle_registration_post'
HANDLE_AUTHENTICATION_POST = 'auth.handle_authentication_post'
HANDLE_UNAUTHENTICATION_POST = 'auth.handle_unauthentication_post'
HANDLE_REFRESHMENT_POST = 'auth.handle_refreshment_post'
HANDLE_CONFIRMATION_POST = 'auth.handle_confirmation_post'
HANDLE_CONFIRMATION_RESENDING_POST = 'auth.handle_confirmation_resending_post'
HANDLE_PASSWORD_FORGOTTEN_POST = 'auth.handle_password_forgotten_post'
HANDLE_PASSWORD_RESETTING_POST = 'auth.handle_password_resetting_post'
