# Scanned bound route handlers for auth:
HANDLE_CONFIRMATION_RESENDING_GET = 'auth.handle_confirmation_resending_get'
HANDLE_CONFIRMATION_GET = 'auth.handle_confirmation_get'
HANDLE_REGISTRATION_POST = 'auth.handle_registration_post'
HANDLE_AUTHENTICATION_POST = 'auth.handle_authentication_post'
HANDLE_REFRESHMENT_POST = 'auth.handle_refreshment_post'
HANDLE_PASSWORD_RESETTING_POST = 'auth.handle_password_resetting_post'
HANDLE_CONFIRMATION_POST = 'auth.handle_confirmation_post'
HANDLE_CONFIRMATION_RESENDING_POST = 'auth.handle_confirmation_resending_post'
HANDLE_EMAIL_PASSWORD_RESET_POST = 'auth.handle_email_password_reset_post'
