ACCESS_TOKEN_COOKIE = "access-token"
REFRESH_TOKEN_COOKIE = "refresh-token"
ACCESS_TOKEN_COOKIE_EXPIRY_SECONDS = 300
REFRESH_TOKEN_COOKIE_SHORT_EXPIRY_SECONDS = 86400
REFRESH_TOKEN_COOKIE_LONG_EXPIRY_SECONDS = 604800