import os


# Scanned directory names
ROOT_DIR = 'templates'
TEMPLATES_ERROR_DIR = 'error'
TEMPLATES_INCLUDE_DIR = 'include'
TEMPLATES_LAYOUT_DIR = 'layout'
TEMPLATES_MODAL_DIR = 'modal'
TEMPLATES_SECTION_DIR = 'section'

# Scanned file names
ERROR_ERROR_FILE = 'error.html'
INCLUDE_BOOTSTRAP_INCLUDES_FILE = 'bootstrap-includes.html'
INCLUDE_MATERIAL_DESIGN_INCLUDES_FILE = 'material-design-includes.html'
LAYOUT_BASE_FILE = 'base.html'
LAYOUT_LAYOUT_FILE = 'layout.html'
MODAL_LOGIN_FILE = 'login.html'
SECTION_CRAWLED_CONTENT_FILE = 'crawled_content.html'
SECTION_HOME_FILE = 'home.html'

# Scanned file paths
ERROR_ERROR_PATH = '/'.join((os.curdir, TEMPLATES_ERROR_DIR, ERROR_ERROR_FILE))
INCLUDE_BOOTSTRAP_INCLUDES_PATH = '/'.join((os.curdir, TEMPLATES_INCLUDE_DIR, INCLUDE_BOOTSTRAP_INCLUDES_FILE))
INCLUDE_MATERIAL_DESIGN_INCLUDES_PATH = '/'.join((os.curdir, TEMPLATES_INCLUDE_DIR, INCLUDE_MATERIAL_DESIGN_INCLUDES_FILE))
LAYOUT_BASE_PATH = '/'.join((os.curdir, TEMPLATES_LAYOUT_DIR, LAYOUT_BASE_FILE))
LAYOUT_LAYOUT_PATH = '/'.join((os.curdir, TEMPLATES_LAYOUT_DIR, LAYOUT_LAYOUT_FILE))
MODAL_LOGIN_PATH = '/'.join((os.curdir, TEMPLATES_MODAL_DIR, MODAL_LOGIN_FILE))
SECTION_CRAWLED_CONTENT_PATH = '/'.join((os.curdir, TEMPLATES_SECTION_DIR, SECTION_CRAWLED_CONTENT_FILE))
SECTION_HOME_PATH = '/'.join((os.curdir, TEMPLATES_SECTION_DIR, SECTION_HOME_FILE))

