import os


# Scanned directory names
ROOT_DIR = 'templates'
TEMPLATES_INCLUDE_DIR = 'include'
TEMPLATES_INDIVIDUAL_DIR = 'individual'
TEMPLATES_LAYOUT_DIR = 'layout'
TEMPLATES_MODAL_DIR = 'modal'
TEMPLATES_SECTION_DIR = 'section'

# Scanned file names
INCLUDE_BOOTSTRAP_INCLUDES_FILE = 'bootstrap-includes.html'
INCLUDE_MATERIAL_DESIGN_INCLUDES_FILE = 'material-design-includes.html'
INDIVIDUAL_ERROR_FILE = 'error.html'
LAYOUT_AUTH_TOOLBAR_FILE = 'auth_toolbar.html'
LAYOUT_BASE_FILE = 'base.html'
LAYOUT_LAYOUT_FILE = 'layout.html'
LAYOUT_NOAUTH_TOOLBAR_FILE = 'noauth_toolbar.html'
MODAL_ACCOUNT_UPDATED_FILE = 'account_updated.html'
MODAL_BAD_TOKEN_FILE = 'bad-token.html'
MODAL_CONFIRM_FILE = 'confirm.html'
MODAL_LOGIN_FILE = 'login.html'
MODAL_LOGOUT_FILE = 'logout.html'
MODAL_MULTI_CHOICE_FILE = 'multi-choice.html'
MODAL_NOTIFICATION_SENT_FILE = 'notification-sent.html'
MODAL_PASSWORD_RESET_FILE = 'password-reset.html'
SECTION_ACTIVITY_ACTIVE_FILE = 'activity_active.html'
SECTION_ACTIVITY_INACTIVE_FILE = 'activity_inactive.html'
SECTION_ARCHIVE_FILE = 'archive.html'
SECTION_CONFIGURATION_FILE = 'configuration.html'
SECTION_HOME_FILE = 'home.html'

# Scanned file paths
INCLUDE_BOOTSTRAP_INCLUDES_PATH = '/'.join((TEMPLATES_INCLUDE_DIR, INCLUDE_BOOTSTRAP_INCLUDES_FILE))
INCLUDE_MATERIAL_DESIGN_INCLUDES_PATH = '/'.join((TEMPLATES_INCLUDE_DIR, INCLUDE_MATERIAL_DESIGN_INCLUDES_FILE))
INDIVIDUAL_ERROR_PATH = '/'.join((TEMPLATES_INDIVIDUAL_DIR, INDIVIDUAL_ERROR_FILE))
LAYOUT_AUTH_TOOLBAR_PATH = '/'.join((TEMPLATES_LAYOUT_DIR, LAYOUT_AUTH_TOOLBAR_FILE))
LAYOUT_BASE_PATH = '/'.join((TEMPLATES_LAYOUT_DIR, LAYOUT_BASE_FILE))
LAYOUT_LAYOUT_PATH = '/'.join((TEMPLATES_LAYOUT_DIR, LAYOUT_LAYOUT_FILE))
LAYOUT_NOAUTH_TOOLBAR_PATH = '/'.join((TEMPLATES_LAYOUT_DIR, LAYOUT_NOAUTH_TOOLBAR_FILE))
MODAL_ACCOUNT_UPDATED_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_ACCOUNT_UPDATED_FILE))
MODAL_BAD_TOKEN_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_BAD_TOKEN_FILE))
MODAL_CONFIRM_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_CONFIRM_FILE))
MODAL_LOGIN_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_LOGIN_FILE))
MODAL_LOGOUT_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_LOGOUT_FILE))
MODAL_MULTI_CHOICE_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_MULTI_CHOICE_FILE))
MODAL_NOTIFICATION_SENT_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_NOTIFICATION_SENT_FILE))
MODAL_PASSWORD_RESET_PATH = '/'.join((TEMPLATES_MODAL_DIR, MODAL_PASSWORD_RESET_FILE))
SECTION_ACTIVITY_ACTIVE_PATH = '/'.join((TEMPLATES_SECTION_DIR, SECTION_ACTIVITY_ACTIVE_FILE))
SECTION_ACTIVITY_INACTIVE_PATH = '/'.join((TEMPLATES_SECTION_DIR, SECTION_ACTIVITY_INACTIVE_FILE))
SECTION_ARCHIVE_PATH = '/'.join((TEMPLATES_SECTION_DIR, SECTION_ARCHIVE_FILE))
SECTION_CONFIGURATION_PATH = '/'.join((TEMPLATES_SECTION_DIR, SECTION_CONFIGURATION_FILE))
SECTION_HOME_PATH = '/'.join((TEMPLATES_SECTION_DIR, SECTION_HOME_FILE))

