URL_STORAGE = "/url-storage"
NEXT_URL = "/next-url"
PARSED_CONTENT = "/parsed-content"
PARSED_IMAGE = "/parsed-image"
MEMORY_LIMIT = "/memory-limit"
MEMORY_USAGE = "/memory-usage"
CONTENT_SOURCE = "/content-source"