URL_STORAGE = "/url-storage"
NEXT_URL = "/next-url"
PARSER_CONFIGURATION = "/parser-configuration"
CRAWLER_CONFIGURATION = "/crawler-configuration"
CRAWLER_CONFIGURATION_OPTION = "/crawler-configuration-option"
PARSED_CONTENT = "/parsed-content"
PARSED_IMAGE = "/parsed-image"
MEMORY_LIMIT = "/memory-limit"