import os

APP_HOST = os.environ['CLIENT_HOST']
APP_PORT = os.environ['CLIENT_PORT']

AUTH_CONTAINER_NAME = os.environ['AUTH_CONTAINER_NAME']
NOTIFICATION_CONTAINER_NAME = os.environ['NOTIFICATION_CONTAINER_NAME']
CRAWLER_CONTAINER_NAME = os.environ['CRAWLER_CONTAINER_NAME']
CONFIG_CONTAINER_NAME = os.environ['CONFIG_CONTAINER_NAME']
PARSER_CONTAINER_NAME = os.environ['PARSER_CONTAINER_NAME']
STORAGE_CONTAINER_NAME = os.environ['STORAGE_CONTAINER_NAME']

AUTH_PORT = os.environ['AUTH_PORT']
NOTIFICATION_PORT = os.environ['NOTIFICATION_PORT']
CRAWLER_PORT = os.environ['CRAWLER_PORT']
CONFIG_PORT = os.environ['CONFIG_PORT']
PARSER_PORT = os.environ['PARSER_PORT']
STORAGE_PORT = os.environ['STORAGE_PORT']