import os

APP_HOST = os.environ['CRAWLER_HOST']
APP_PORT = os.environ['CRAWLER_PORT']

CACHE_CONTAINER_NAME = os.environ['CACHE_CONTAINER_NAME']
STORAGE_CONTAINER_NAME = os.environ['STORAGE_CONTAINER_NAME']
CONFIG_CONTAINER_NAME = os.environ['CONFIG_CONTAINER_NAME']
AMQP_CONTAINER_NAME = os.environ["AMQP_CONTAINER_NAME"]

CACHE_PORT = os.environ['CACHE_PORT']
STORAGE_PORT = os.environ['STORAGE_PORT']
CONFIG_PORT = os.environ['CONFIG_PORT']
AMQP_PORT = os.environ["AMQP_PORT"]


AMQP_USERNAME = os.environ["AMQP_USERNAME"]
AMQP_PASSWORD = os.environ["AMQP_PASSWORD"]
AMQP_QUEUE = os.environ["AMQP_QUEUE"]