CRAWLER = "/crawler"
PARSER = "/parser"
NEXT_LINK = "/next-link"
CLIENT = "/client"
CRAWLED_CONTENT = "/crawled-content"
STORAGE_MS_URL= "http://localhost:50006"
PARSER_MS_URL= "http://localhost:50005"