CRAWLER = "/crawler"
PARSER = "/parser"
NEXT_LINK = "/next-link"
CRAWLER_CONFIG = "/crawler-config"
STORAGE_MS_URL = "http://localhost:50006"
PARSER_MS_URL = "http://localhost:50005"
CONFIG_MS_URL = "http://localhost:50004"