import os

APP_HOST = os.environ['CONFIG_HOST']
APP_PORT = os.environ['CONFIG_PORT']

DB_USERNAME = os.environ['CONFIG_POSTGRES_USERNAME']
DB_PASSWORD = os.environ['CONFIG_POSTGRES_PASSWORD']
DB_DATABASE = os.environ['CONFIG_POSTGRES_DATABASE']
DB_CONTAINER_NAME = os.environ['CONFIG_POSTGRES_CONTAINER_NAME']
DB_PORT = os.environ['CONFIG_POSTGRES_PORT']