import os

APP_HOST = os.environ['STORAGE_HOST']
APP_PORT = os.environ['STORAGE_PORT']

DB_USERNAME = os.environ['STORAGE_POSTGRES_USERNAME']
DB_PASSWORD = os.environ['STORAGE_POSTGRES_PASSWORD']
DB_DATABASE = os.environ['STORAGE_POSTGRES_DATABASE']
DB_CONTAINER_NAME = os.environ['STORAGE_POSTGRES_CONTAINER_NAME']
DB_PORT = os.environ['STORAGE_POSTGRES_PORT']