version: '3.8'

services:
  postgres_auth:
    container_name: ${AUTH_POSTGRES_CONTAINER_NAME}
    image: postgres
    environment:
      - CREATE_USER_INTERACTIVE=off
      - POSTGRES_USER=${AUTH_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DATABASE}
    volumes:
      - ./auth/init/sql:/docker-entrypoint-initdb.d
    networks:
      - msauth
    ports:
      - ${AUTH_POSTGRES_PORT}:${AUTH_POSTGRES_PORT}
    command: -p ${AUTH_POSTGRES_PORT}

  redis_auth:
    container_name: ${AUTH_REDIS_CONTAINER_NAME}
    image: redis    
    networks:
      - msauth
    ports:
      - ${AUTH_REDIS_PORT}:${AUTH_REDIS_PORT}
    command: >
      --requirepass ${AUTH_REDIS_PASSWORD}
      --port ${AUTH_REDIS_PORT}

  redis_cache:
    container_name: ${CACHE_REDIS_CONTAINER_NAME}
    image: redis    
    networks:
      - msauth
    ports:
      - ${CACHE_REDIS_PORT}:${CACHE_REDIS_PORT}
    command: >
      --requirepass ${CACHE_REDIS_PASSWORD}
      --port ${CACHE_REDIS_PORT}
  
  rabbitmq:
    container_name: ${AMQP_CONTAINER_NAME}
    #hostname: rabbitmq
    networks:
      - msauth
    image:
      rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
      - RABBITMQ_NODE_PORT=${AMQP_PORT}
      - RABBIT_HOST_IP=${AMQP_HOST}
    ports:
      - 15672:15672
      - ${AMQP_PORT}:${AMQP_PORT}

networks:
  msauth:
    external: true
    name: msauth