version: '3.9'
services:
  redis:
    container_name: redis-crawler
    image: redis:alpine
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    logging:
      options:
        max-size: 10m
        max-file: "3"
    # network_mode: "host"
    ports:
      - '6380:6380'
    volumes:
      - ./redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]